#http://docs.travis-ci.com/user/languages/android/

language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19

install:
#ant deps

before_script:
  -export ANDROID_TARGET=android-21
  -android update project -p . $ANDROID_TARGET

script:
  -ant debug
